### ISSUE TITLE
undefined function

### ISSUE THREAD

**Issue by fcpauldiaz** [byteclubfr/socket.io-monitor#2]
When I try to config this module.
```js
import monitor from 'socket.io-monitor';

const io = socket.listen(server);
const { serverSocket } = monitor.bind(io, { port: 9042, host: 'localhost' })

  serverSocket.then(srv => {
    console.log('connection OK')
  })
```
I get this error
```bash
TypeError: Cannot read property 'then' of undefined
```

I'm using socket-io 2.3

**Comment by fcpauldiaz** [comment]
@naholyr @Delapouite

**Comment by naholyr** [comment]
Thanks for the report, I'm on it :)

**Comment by naholyr** [comment]
Oh, it doesn't look like a bug but a misuse : ``bind()`` returns an object with properties ``server`` and ``emitter``, and you try to grab property ``serverSocket`` which will be undefined ;)

If you really want to use ``serverSocket`` as local variable's name, you can do that while destructuring:

```js
const { server: serverSocket } = monitor.bind(/*…*/)
```

**Comment by fcpauldiaz** [comment]
Thanks @naholyr! Should update the docs then :)
